name: Deploy

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Evolution Container
        run: |
          docker run -d \
            --name evolution-api \
            -p 8080:8080 \
            -e AUTHENTICATION_API_KEY=${{ secrets.EVOLUTION_SECRET }} \
            -v evolution_store:/evolution/store \
            -v evolution_instances:/evolution/instances \
            atendai/evolution-api

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli

      - name: Install Project Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set Vapor Team
        run: vapor team:switch --id=${{ env.VAPOR_API_TEAM}}
        env:
          VAPOR_API_TEAM: ${{ secrets.VAPOR_TEAM_ID }}
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}

      - name: Check Docker Logs
        run: docker logs evolution-api
