name: Deploy Project

on:
  push:
    branches:
      - Production
      - Staging
jobs:
  deploy:
    name: Deploy project with Nginx
    permissions:
      deployments: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v2"
        with:
          ref: Production
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ github.token }}"
          environment-url: ${{ secrets.APP_URL }}
          environment: production

      - name: Set up SSH Key and Deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          passphrase: ""
          port: 22
          script: |
            git config --global url."https://${{ secrets.PERSONAL_GITHUB_TOKEN }}:@github.com".insteadOf "https://github.com"

            cd ${{secrets.APP_PATH}}

            git pull origin production

            composer install

            php artisan migrate --force
            php artisan config:cache
            php artisan event:cache
            php artisan octane:restart
            php artisan optimize:clear
            php artisan optimize
            pm2 restart all --watch --update-env

            sudo service nginx restart

      - name: Update deployment Status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ secrets.APP_URL }}
          state: "success"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: "${{ github.token }}"
          environment-url: ${{ secrets.APP_URL }}
          state: "failure"
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
